雪が溶け残る確率を計算してみる。  
```np_r``` 多次元配列の結合。[ ]内に結合したい配列と結合の仕方を記述する。  
```reshape``` 指定した配列パターンに変換する。-1とした場合は他の次元の指定値から推測されて自動的に決定される。  
```np.ones(a)``` a個分の"1"が入った配列を生成。  
```np.zeros(a)``` a個分の"1"が入った配列を生成。  
```predict_proba``` 与えたサンプル値に対し、各クラスに属する確率を返す。

In [9]:
import numpy as np
from sklearn.linear_model import LogisticRegression

X_train = np.r_[np.random.normal(3, 1, size = 50),
          np.random.normal(-1, 1, size = 50)].reshape((100, -1))
y_train = np.r_[np.ones(50), np.zeros(50)]
model = LogisticRegression()
model.fit(X_train, y_train)
model.predict_proba([[0], [1], [2]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([[0.86207239, 0.13792761],
       [0.41504471, 0.58495529],
       [0.0745432 , 0.9254568 ]])

```predict_proba```の結果はクラス0が雪が残る、クラス1が雪が溶ける、なので、溶ける確率だけを取り出す。

In [11]:
model.predict_proba([[0], [1], [2]])[:, 1]

array([0.13792761, 0.58495529, 0.9254568 ])

In [10]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])