## 3.5.1 恒等関数とソフトマックス関数

In [2]:
import numpy as np
a= np.array([0.3,2.9,4.0])
exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [3]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [4]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [5]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

## 3.5.2 ソフトマックス関数の実装上の注意

In [9]:
a = np.array([1010,1000,990])
exp = np.exp(a) / np.sum(np.exp(a))
print(exp)

[nan nan nan]


<ipython-input-9-4c24e1f95862>:2: RuntimeWarning: overflow encountered in exp
  exp = np.exp(a) / np.sum(np.exp(a))
<ipython-input-9-4c24e1f95862>:2: RuntimeWarning: invalid value encountered in true_divide
  exp = np.exp(a) / np.sum(np.exp(a))


In [10]:
c = np.max(a)
a2 = a - c
exp2 = np.exp(a2) / np.sum(np.exp(a2))

In [11]:
print(exp2)

[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [13]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y